### Users Table
GET http://localhost:3000/users


### Registeration
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "parni",
    "email": "parnika@gmail.com",
    "password": "Parni@Teja123"
}

### Signin User
POST http://localhost:3000/api/signin
Content-Type: application/json 

{
    "email": "parnika@gmail.com",
    "password": "Parni@Teja123"
}