### Users Table
GET http://localhost:3000/users


### Registeration
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "first_name": "Parnika Bala",
    "last_name": "Neeli",
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123",
    "Date_of_birth": "2001-04-21",
    "enabled": 1
}

### Signin User
POST http://localhost:3000/api/signin
Content-Type: application/json 

{
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123"
}