### Users Table
GET http://localhost:3000/users


### Registeration
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Parnika Bala",
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123"
}

### Signin User
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email": "parnikaneeli@gmail.com",
    "password": "Parni@Teja123"
}
###

GET http://localhost:3000/api/userpayment
###

POST http://localhost:3000/api/paymentDetails1
Content-Type: application/json

{
    "email": "parnikaneeli@gmail.com",
    "planId": 1,
    "billingCycle": "half year", 
    "paymentMethod": "card", 
    "cardNum": "1478523698745632", 
    "cardExpiryDate": "2025-02-01"
}
###
POST http://localhost:3000/api/paymentDetails1
Content-Type: application/json

{
    "email": "parnikaneeli@gmail.com",
    "planId": 1,
    "billingCycle": "half year", 
    "paymentMethod": "upi",
    "upiId" : "14789526@frgr"
}
###

POST http://localhost:3000/api/user/payment
Content-Type: application/json

{
    "fullName" : "Tejaswi",
    "cardNumber": "12432546987521",
    "expirationDate":"2027-12-12",
    "country":"India",
    "state": "Telangana",
    "city": "Mahabubabad",
    "addressLine1": "2-2B Shivashankar cloth store",
    "addressLine2": "Bus stand road",
    "postalCode": 101505,
    "billingCycle": "Annually",
    "termsAccepted": false,
    "planId": 1
}

###Companys_socks_list
GET http://localhost:3000/api/compstock/1


###Nifty100 from company_stocklist
GET http://localhost:3000/api/nifty100


###
GET http://localhost:3000/api/stocks

###Companys_socks_list
GET http://localhost:3000/api/compstock

###
GET http://localhost:3000/api/nifty500


###

<!--POST http://localhost:3000/api/user/paymentpaypal
Content-Type: application/json

{
    "fullName": "Parnika Bala",
    "phoneNumber": "9578523641",
    "country": "India",
    "state": "Telangan",
    "city": "Mahabubabad",
    "addressLine1": "kjdfbuwr sdofnwroi",
    "addressLine2": "niowbhru9 wuogfbwruoe",
    "postalCode": "589625",
    "billingCycle": "Annually",
    "termsAccepted": false,
    "planId": 1
}

###

POST http://localhost:3000/api/user/upi/payment
Content-Type: application/json

{
    "fullName": "Parnika Bala",
    "phoneNumber": "9900085658",
    "country": "India",
    "email": "parnika@gmail.com",
    "state": "Telangana",
    "pan":"1425FRH54",
    "city": "Mahabubabad",
    "addressLine1": "jbhvutrtxfchjb",
    "addressLine2": "fegrhtejyr",
    "postalCode": "521465",
    "billingCycle": "Annually",
    "termsAccepted": false,
    "planId": 2
}-->
###
#DELETE http://localhost:3000/api/deleteuserpatment/


###

<!--DELETE http://localhost:3000/deleteplan/
###

DELETE  http://localhost:3000/deleteplancompanies-->